# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/benoit/gadgetron_install_dir/gadgetron4_sms/mrprogs/gadgetron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/benoit/gadgetron_install_dir/gadgetron4_sms/mrprogs/gadgetron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/benoit/gadgetron_install_dir/gadgetron4_sms/mrprogs/gadgetron/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"main\" \"scripts\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benoit/gadgetron_install_dir/gadgetron4_sms/mrprogs/gadgetron/CMakeFiles /home/benoit/gadgetron_install_dir/gadgetron4_sms/mrprogs/gadgetron/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benoit/gadgetron_install_dir/gadgetron4_sms/mrprogs/gadgetron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gadgetron_core

# Build rule for target.
gadgetron_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_core
.PHONY : gadgetron_core

# fast build rule for target.
gadgetron_core/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/gadgetron_core.dir/build.make core/CMakeFiles/gadgetron_core.dir/build
.PHONY : gadgetron_core/fast

#=============================================================================
# Target rules for targets named gadgetron_core_readers

# Build rule for target.
gadgetron_core_readers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_core_readers
.PHONY : gadgetron_core_readers

# fast build rule for target.
gadgetron_core_readers/fast:
	$(MAKE) $(MAKESILENT) -f core/readers/CMakeFiles/gadgetron_core_readers.dir/build.make core/readers/CMakeFiles/gadgetron_core_readers.dir/build
.PHONY : gadgetron_core_readers/fast

#=============================================================================
# Target rules for targets named gadgetron_core_writers

# Build rule for target.
gadgetron_core_writers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_core_writers
.PHONY : gadgetron_core_writers

# fast build rule for target.
gadgetron_core_writers/fast:
	$(MAKE) $(MAKESILENT) -f core/writers/CMakeFiles/gadgetron_core_writers.dir/build.make core/writers/CMakeFiles/gadgetron_core_writers.dir/build
.PHONY : gadgetron_core_writers/fast

#=============================================================================
# Target rules for targets named gadgetron_core_parallel

# Build rule for target.
gadgetron_core_parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_core_parallel
.PHONY : gadgetron_core_parallel

# fast build rule for target.
gadgetron_core_parallel/fast:
	$(MAKE) $(MAKESILENT) -f core/parallel/CMakeFiles/gadgetron_core_parallel.dir/build.make core/parallel/CMakeFiles/gadgetron_core_parallel.dir/build
.PHONY : gadgetron_core_parallel/fast

#=============================================================================
# Target rules for targets named gadgetron_core_distributed

# Build rule for target.
gadgetron_core_distributed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_core_distributed
.PHONY : gadgetron_core_distributed

# fast build rule for target.
gadgetron_core_distributed/fast:
	$(MAKE) $(MAKESILENT) -f core/distributed/CMakeFiles/gadgetron_core_distributed.dir/build.make core/distributed/CMakeFiles/gadgetron_core_distributed.dir/build
.PHONY : gadgetron_core_distributed/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_log

# Build rule for target.
gadgetron_toolbox_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_log
.PHONY : gadgetron_toolbox_log

# fast build rule for target.
gadgetron_toolbox_log/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/log/CMakeFiles/gadgetron_toolbox_log.dir/build.make toolboxes/log/CMakeFiles/gadgetron_toolbox_log.dir/build
.PHONY : gadgetron_toolbox_log/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpuoperator

# Build rule for target.
gadgetron_toolbox_cpuoperator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpuoperator
.PHONY : gadgetron_toolbox_cpuoperator

# fast build rule for target.
gadgetron_toolbox_cpuoperator/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/operators/cpu/CMakeFiles/gadgetron_toolbox_cpuoperator.dir/build.make toolboxes/operators/cpu/CMakeFiles/gadgetron_toolbox_cpuoperator.dir/build
.PHONY : gadgetron_toolbox_cpuoperator/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpuoperators

# Build rule for target.
gadgetron_toolbox_gpuoperators: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpuoperators
.PHONY : gadgetron_toolbox_gpuoperators

# fast build rule for target.
gadgetron_toolbox_gpuoperators/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/operators/gpu/CMakeFiles/gadgetron_toolbox_gpuoperators.dir/build.make toolboxes/operators/gpu/CMakeFiles/gadgetron_toolbox_gpuoperators.dir/build
.PHONY : gadgetron_toolbox_gpuoperators/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpusolvers

# Build rule for target.
gadgetron_toolbox_gpusolvers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpusolvers
.PHONY : gadgetron_toolbox_gpusolvers

# fast build rule for target.
gadgetron_toolbox_gpusolvers/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/solvers/gpu/CMakeFiles/gadgetron_toolbox_gpusolvers.dir/build.make toolboxes/solvers/gpu/CMakeFiles/gadgetron_toolbox_gpusolvers.dir/build
.PHONY : gadgetron_toolbox_gpusolvers/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpufft

# Build rule for target.
gadgetron_toolbox_cpufft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpufft
.PHONY : gadgetron_toolbox_cpufft

# fast build rule for target.
gadgetron_toolbox_cpufft/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/fft/cpu/CMakeFiles/gadgetron_toolbox_cpufft.dir/build.make toolboxes/fft/cpu/CMakeFiles/gadgetron_toolbox_cpufft.dir/build
.PHONY : gadgetron_toolbox_cpufft/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpufft

# Build rule for target.
gadgetron_toolbox_gpufft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpufft
.PHONY : gadgetron_toolbox_gpufft

# fast build rule for target.
gadgetron_toolbox_gpufft/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/fft/gpu/CMakeFiles/gadgetron_toolbox_gpufft.dir/build.make toolboxes/fft/gpu/CMakeFiles/gadgetron_toolbox_gpufft.dir/build
.PHONY : gadgetron_toolbox_gpufft/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpucore

# Build rule for target.
gadgetron_toolbox_cpucore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpucore
.PHONY : gadgetron_toolbox_cpucore

# fast build rule for target.
gadgetron_toolbox_cpucore/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/core/cpu/CMakeFiles/gadgetron_toolbox_cpucore.dir/build.make toolboxes/core/cpu/CMakeFiles/gadgetron_toolbox_cpucore.dir/build
.PHONY : gadgetron_toolbox_cpucore/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpucore_math

# Build rule for target.
gadgetron_toolbox_cpucore_math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpucore_math
.PHONY : gadgetron_toolbox_cpucore_math

# fast build rule for target.
gadgetron_toolbox_cpucore_math/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/core/cpu/math/CMakeFiles/gadgetron_toolbox_cpucore_math.dir/build.make toolboxes/core/cpu/math/CMakeFiles/gadgetron_toolbox_cpucore_math.dir/build
.PHONY : gadgetron_toolbox_cpucore_math/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_hostutils

# Build rule for target.
gadgetron_toolbox_hostutils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_hostutils
.PHONY : gadgetron_toolbox_hostutils

# fast build rule for target.
gadgetron_toolbox_hostutils/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/core/cpu/hostutils/CMakeFiles/gadgetron_toolbox_hostutils.dir/build.make toolboxes/core/cpu/hostutils/CMakeFiles/gadgetron_toolbox_hostutils.dir/build
.PHONY : gadgetron_toolbox_hostutils/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpucore

# Build rule for target.
gadgetron_toolbox_gpucore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpucore
.PHONY : gadgetron_toolbox_gpucore

# fast build rule for target.
gadgetron_toolbox_gpucore/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/core/gpu/CMakeFiles/gadgetron_toolbox_gpucore.dir/build.make toolboxes/core/gpu/CMakeFiles/gadgetron_toolbox_gpucore.dir/build
.PHONY : gadgetron_toolbox_gpucore/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_mri_core_python

# Build rule for target.
gadgetron_toolbox_mri_core_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_mri_core_python
.PHONY : gadgetron_toolbox_mri_core_python

# fast build rule for target.
gadgetron_toolbox_mri_core_python/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/mri_core/CMakeFiles/gadgetron_toolbox_mri_core_python.dir/build.make toolboxes/mri_core/CMakeFiles/gadgetron_toolbox_mri_core_python.dir/build
.PHONY : gadgetron_toolbox_mri_core_python/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_mri_core

# Build rule for target.
gadgetron_toolbox_mri_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_mri_core
.PHONY : gadgetron_toolbox_mri_core

# fast build rule for target.
gadgetron_toolbox_mri_core/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/mri_core/CMakeFiles/gadgetron_toolbox_mri_core.dir/build.make toolboxes/mri_core/CMakeFiles/gadgetron_toolbox_mri_core.dir/build
.PHONY : gadgetron_toolbox_mri_core/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpuparallelmri

# Build rule for target.
gadgetron_toolbox_gpuparallelmri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpuparallelmri
.PHONY : gadgetron_toolbox_gpuparallelmri

# fast build rule for target.
gadgetron_toolbox_gpuparallelmri/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/mri/pmri/gpu/CMakeFiles/gadgetron_toolbox_gpuparallelmri.dir/build.make toolboxes/mri/pmri/gpu/CMakeFiles/gadgetron_toolbox_gpuparallelmri.dir/build
.PHONY : gadgetron_toolbox_gpuparallelmri/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_hyper

# Build rule for target.
gadgetron_toolbox_hyper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_hyper
.PHONY : gadgetron_toolbox_hyper

# fast build rule for target.
gadgetron_toolbox_hyper/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/mri/hyper/CMakeFiles/gadgetron_toolbox_hyper.dir/build.make toolboxes/mri/hyper/CMakeFiles/gadgetron_toolbox_hyper.dir/build
.PHONY : gadgetron_toolbox_hyper/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cmr

# Build rule for target.
gadgetron_toolbox_cmr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cmr
.PHONY : gadgetron_toolbox_cmr

# fast build rule for target.
gadgetron_toolbox_cmr/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/cmr/CMakeFiles/gadgetron_toolbox_cmr.dir/build.make toolboxes/cmr/CMakeFiles/gadgetron_toolbox_cmr.dir/build
.PHONY : gadgetron_toolbox_cmr/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpuklt

# Build rule for target.
gadgetron_toolbox_cpuklt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpuklt
.PHONY : gadgetron_toolbox_cpuklt

# fast build rule for target.
gadgetron_toolbox_cpuklt/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/klt/cpu/CMakeFiles/gadgetron_toolbox_cpuklt.dir/build.make toolboxes/klt/cpu/CMakeFiles/gadgetron_toolbox_cpuklt.dir/build
.PHONY : gadgetron_toolbox_cpuklt/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_fatwater

# Build rule for target.
gadgetron_toolbox_fatwater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_fatwater
.PHONY : gadgetron_toolbox_fatwater

# fast build rule for target.
gadgetron_toolbox_fatwater/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/fatwater/CMakeFiles/gadgetron_toolbox_fatwater.dir/build.make toolboxes/fatwater/CMakeFiles/gadgetron_toolbox_fatwater.dir/build
.PHONY : gadgetron_toolbox_fatwater/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_deblur

# Build rule for target.
gadgetron_toolbox_deblur: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_deblur
.PHONY : gadgetron_toolbox_deblur

# fast build rule for target.
gadgetron_toolbox_deblur/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/deblur/CMakeFiles/gadgetron_toolbox_deblur.dir/build.make toolboxes/deblur/CMakeFiles/gadgetron_toolbox_deblur.dir/build
.PHONY : gadgetron_toolbox_deblur/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpunfft

# Build rule for target.
gadgetron_toolbox_gpunfft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpunfft
.PHONY : gadgetron_toolbox_gpunfft

# fast build rule for target.
gadgetron_toolbox_gpunfft/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/nfft/gpu/CMakeFiles/gadgetron_toolbox_gpunfft.dir/build.make toolboxes/nfft/gpu/CMakeFiles/gadgetron_toolbox_gpunfft.dir/build
.PHONY : gadgetron_toolbox_gpunfft/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpunfft

# Build rule for target.
gadgetron_toolbox_cpunfft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpunfft
.PHONY : gadgetron_toolbox_cpunfft

# fast build rule for target.
gadgetron_toolbox_cpunfft/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/nfft/cpu/CMakeFiles/gadgetron_toolbox_cpunfft.dir/build.make toolboxes/nfft/cpu/CMakeFiles/gadgetron_toolbox_cpunfft.dir/build
.PHONY : gadgetron_toolbox_cpunfft/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpudwt

# Build rule for target.
gadgetron_toolbox_gpudwt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpudwt
.PHONY : gadgetron_toolbox_gpudwt

# fast build rule for target.
gadgetron_toolbox_gpudwt/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/dwt/gpu/CMakeFiles/gadgetron_toolbox_gpudwt.dir/build.make toolboxes/dwt/gpu/CMakeFiles/gadgetron_toolbox_gpudwt.dir/build
.PHONY : gadgetron_toolbox_gpudwt/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpudwt

# Build rule for target.
gadgetron_toolbox_cpudwt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpudwt
.PHONY : gadgetron_toolbox_cpudwt

# fast build rule for target.
gadgetron_toolbox_cpudwt/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/dwt/cpu/CMakeFiles/gadgetron_toolbox_cpudwt.dir/build.make toolboxes/dwt/cpu/CMakeFiles/gadgetron_toolbox_cpudwt.dir/build
.PHONY : gadgetron_toolbox_cpudwt/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpureg

# Build rule for target.
gadgetron_toolbox_cpureg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpureg
.PHONY : gadgetron_toolbox_cpureg

# fast build rule for target.
gadgetron_toolbox_cpureg/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/registration/optical_flow/cpu/CMakeFiles/gadgetron_toolbox_cpureg.dir/build.make toolboxes/registration/optical_flow/cpu/CMakeFiles/gadgetron_toolbox_cpureg.dir/build
.PHONY : gadgetron_toolbox_cpureg/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_gpureg

# Build rule for target.
gadgetron_toolbox_gpureg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_gpureg
.PHONY : gadgetron_toolbox_gpureg

# fast build rule for target.
gadgetron_toolbox_gpureg/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/registration/optical_flow/gpu/CMakeFiles/gadgetron_toolbox_gpureg.dir/build.make toolboxes/registration/optical_flow/gpu/CMakeFiles/gadgetron_toolbox_gpureg.dir/build
.PHONY : gadgetron_toolbox_gpureg/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_demons

# Build rule for target.
gadgetron_toolbox_demons: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_demons
.PHONY : gadgetron_toolbox_demons

# fast build rule for target.
gadgetron_toolbox_demons/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/registration/demons/CMakeFiles/gadgetron_toolbox_demons.dir/build.make toolboxes/registration/demons/CMakeFiles/gadgetron_toolbox_demons.dir/build
.PHONY : gadgetron_toolbox_demons/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_cpu_image

# Build rule for target.
gadgetron_toolbox_cpu_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_cpu_image
.PHONY : gadgetron_toolbox_cpu_image

# fast build rule for target.
gadgetron_toolbox_cpu_image/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/image/cpu/CMakeFiles/gadgetron_toolbox_cpu_image.dir/build.make toolboxes/image/cpu/CMakeFiles/gadgetron_toolbox_cpu_image.dir/build
.PHONY : gadgetron_toolbox_cpu_image/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_pr

# Build rule for target.
gadgetron_toolbox_pr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_pr
.PHONY : gadgetron_toolbox_pr

# fast build rule for target.
gadgetron_toolbox_pr/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/pattern_recognition/CMakeFiles/gadgetron_toolbox_pr.dir/build.make toolboxes/pattern_recognition/CMakeFiles/gadgetron_toolbox_pr.dir/build
.PHONY : gadgetron_toolbox_pr/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_denoise

# Build rule for target.
gadgetron_toolbox_denoise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_denoise
.PHONY : gadgetron_toolbox_denoise

# fast build rule for target.
gadgetron_toolbox_denoise/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/denoise/CMakeFiles/gadgetron_toolbox_denoise.dir/build.make toolboxes/denoise/CMakeFiles/gadgetron_toolbox_denoise.dir/build
.PHONY : gadgetron_toolbox_denoise/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_image_analyze_io

# Build rule for target.
gadgetron_toolbox_image_analyze_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_image_analyze_io
.PHONY : gadgetron_toolbox_image_analyze_io

# fast build rule for target.
gadgetron_toolbox_image_analyze_io/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/image_io/CMakeFiles/gadgetron_toolbox_image_analyze_io.dir/build.make toolboxes/image_io/CMakeFiles/gadgetron_toolbox_image_analyze_io.dir/build
.PHONY : gadgetron_toolbox_image_analyze_io/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_t1

# Build rule for target.
gadgetron_toolbox_t1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_t1
.PHONY : gadgetron_toolbox_t1

# fast build rule for target.
gadgetron_toolbox_t1/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/T1/CMakeFiles/gadgetron_toolbox_t1.dir/build.make toolboxes/T1/CMakeFiles/gadgetron_toolbox_t1.dir/build
.PHONY : gadgetron_toolbox_t1/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_python

# Build rule for target.
gadgetron_toolbox_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_python
.PHONY : gadgetron_toolbox_python

# fast build rule for target.
gadgetron_toolbox_python/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/python/CMakeFiles/gadgetron_toolbox_python.dir/build.make toolboxes/python/CMakeFiles/gadgetron_toolbox_python.dir/build
.PHONY : gadgetron_toolbox_python/fast

#=============================================================================
# Target rules for targets named python_demo

# Build rule for target.
python_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 python_demo
.PHONY : python_demo

# fast build rule for target.
python_demo/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/python/example/CMakeFiles/python_demo.dir/build.make toolboxes/python/example/CMakeFiles/python_demo.dir/build
.PHONY : python_demo/fast

#=============================================================================
# Target rules for targets named gadgetron_test_python

# Build rule for target.
gadgetron_test_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_test_python
.PHONY : gadgetron_test_python

# fast build rule for target.
gadgetron_test_python/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/python/example/CMakeFiles/gadgetron_test_python.dir/build.make toolboxes/python/example/CMakeFiles/gadgetron_test_python.dir/build
.PHONY : gadgetron_test_python/fast

#=============================================================================
# Target rules for targets named gadgetron_toolbox_plplot

# Build rule for target.
gadgetron_toolbox_plplot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_toolbox_plplot
.PHONY : gadgetron_toolbox_plplot

# fast build rule for target.
gadgetron_toolbox_plplot/fast:
	$(MAKE) $(MAKESILENT) -f toolboxes/plplot/CMakeFiles/gadgetron_toolbox_plplot.dir/build.make toolboxes/plplot/CMakeFiles/gadgetron_toolbox_plplot.dir/build
.PHONY : gadgetron_toolbox_plplot/fast

#=============================================================================
# Target rules for targets named gadgetron_examples

# Build rule for target.
gadgetron_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_examples
.PHONY : gadgetron_examples

# fast build rule for target.
gadgetron_examples/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/examples/CMakeFiles/gadgetron_examples.dir/build.make gadgets/examples/CMakeFiles/gadgetron_examples.dir/build
.PHONY : gadgetron_examples/fast

#=============================================================================
# Target rules for targets named gadgetron_mricore

# Build rule for target.
gadgetron_mricore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_mricore
.PHONY : gadgetron_mricore

# fast build rule for target.
gadgetron_mricore/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/mri_core/CMakeFiles/gadgetron_mricore.dir/build.make gadgets/mri_core/CMakeFiles/gadgetron_mricore.dir/build
.PHONY : gadgetron_mricore/fast

#=============================================================================
# Target rules for targets named gadgetron_interventional_mri

# Build rule for target.
gadgetron_interventional_mri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_interventional_mri
.PHONY : gadgetron_interventional_mri

# fast build rule for target.
gadgetron_interventional_mri/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/interventional_mri/CMakeFiles/gadgetron_interventional_mri.dir/build.make gadgets/interventional_mri/CMakeFiles/gadgetron_interventional_mri.dir/build
.PHONY : gadgetron_interventional_mri/fast

#=============================================================================
# Target rules for targets named gadgetron_cmr

# Build rule for target.
gadgetron_cmr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_cmr
.PHONY : gadgetron_cmr

# fast build rule for target.
gadgetron_cmr/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/cmr/CMakeFiles/gadgetron_cmr.dir/build.make gadgets/cmr/CMakeFiles/gadgetron_cmr.dir/build
.PHONY : gadgetron_cmr/fast

#=============================================================================
# Target rules for targets named gadgetron_epi

# Build rule for target.
gadgetron_epi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_epi
.PHONY : gadgetron_epi

# fast build rule for target.
gadgetron_epi/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/epi/CMakeFiles/gadgetron_epi.dir/build.make gadgets/epi/CMakeFiles/gadgetron_epi.dir/build
.PHONY : gadgetron_epi/fast

#=============================================================================
# Target rules for targets named gadgetron_fatwater

# Build rule for target.
gadgetron_fatwater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_fatwater
.PHONY : gadgetron_fatwater

# fast build rule for target.
gadgetron_fatwater/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/fatwater/CMakeFiles/gadgetron_fatwater.dir/build.make gadgets/fatwater/CMakeFiles/gadgetron_fatwater.dir/build
.PHONY : gadgetron_fatwater/fast

#=============================================================================
# Target rules for targets named gadgetron_t1

# Build rule for target.
gadgetron_t1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_t1
.PHONY : gadgetron_t1

# fast build rule for target.
gadgetron_t1/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/T1/CMakeFiles/gadgetron_t1.dir/build.make gadgets/T1/CMakeFiles/gadgetron_t1.dir/build
.PHONY : gadgetron_t1/fast

#=============================================================================
# Target rules for targets named gadgetron_smscore

# Build rule for target.
gadgetron_smscore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_smscore
.PHONY : gadgetron_smscore

# fast build rule for target.
gadgetron_smscore/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/sms_core/CMakeFiles/gadgetron_smscore.dir/build.make gadgets/sms_core/CMakeFiles/gadgetron_smscore.dir/build
.PHONY : gadgetron_smscore/fast

#=============================================================================
# Target rules for targets named gadgetron_thermocore

# Build rule for target.
gadgetron_thermocore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_thermocore
.PHONY : gadgetron_thermocore

# fast build rule for target.
gadgetron_thermocore/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/thermo_core/CMakeFiles/gadgetron_thermocore.dir/build.make gadgets/thermo_core/CMakeFiles/gadgetron_thermocore.dir/build
.PHONY : gadgetron_thermocore/fast

#=============================================================================
# Target rules for targets named gadgetron_gpuparallelmri

# Build rule for target.
gadgetron_gpuparallelmri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_gpuparallelmri
.PHONY : gadgetron_gpuparallelmri

# fast build rule for target.
gadgetron_gpuparallelmri/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/pmri/CMakeFiles/gadgetron_gpuparallelmri.dir/build.make gadgets/pmri/CMakeFiles/gadgetron_gpuparallelmri.dir/build
.PHONY : gadgetron_gpuparallelmri/fast

#=============================================================================
# Target rules for targets named gadgetron_gpuradial

# Build rule for target.
gadgetron_gpuradial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_gpuradial
.PHONY : gadgetron_gpuradial

# fast build rule for target.
gadgetron_gpuradial/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/radial/CMakeFiles/gadgetron_gpuradial.dir/build.make gadgets/radial/CMakeFiles/gadgetron_gpuradial.dir/build
.PHONY : gadgetron_gpuradial/fast

#=============================================================================
# Target rules for targets named gadgetron_hyper

# Build rule for target.
gadgetron_hyper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_hyper
.PHONY : gadgetron_hyper

# fast build rule for target.
gadgetron_hyper/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/hyper/CMakeFiles/gadgetron_hyper.dir/build.make gadgets/hyper/CMakeFiles/gadgetron_hyper.dir/build
.PHONY : gadgetron_hyper/fast

#=============================================================================
# Target rules for targets named gadgetron_gpugadget

# Build rule for target.
gadgetron_gpugadget: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_gpugadget
.PHONY : gadgetron_gpugadget

# fast build rule for target.
gadgetron_gpugadget/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/gpu/CMakeFiles/gadgetron_gpugadget.dir/build.make gadgets/gpu/CMakeFiles/gadgetron_gpugadget.dir/build
.PHONY : gadgetron_gpugadget/fast

#=============================================================================
# Target rules for targets named gadgetron_mri_noncartesian

# Build rule for target.
gadgetron_mri_noncartesian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_mri_noncartesian
.PHONY : gadgetron_mri_noncartesian

# fast build rule for target.
gadgetron_mri_noncartesian/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/mri_noncartesian/CMakeFiles/gadgetron_mri_noncartesian.dir/build.make gadgets/mri_noncartesian/CMakeFiles/gadgetron_mri_noncartesian.dir/build
.PHONY : gadgetron_mri_noncartesian/fast

#=============================================================================
# Target rules for targets named gadgetron_spiral

# Build rule for target.
gadgetron_spiral: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_spiral
.PHONY : gadgetron_spiral

# fast build rule for target.
gadgetron_spiral/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/spiral/CMakeFiles/gadgetron_spiral.dir/build.make gadgets/spiral/CMakeFiles/gadgetron_spiral.dir/build
.PHONY : gadgetron_spiral/fast

#=============================================================================
# Target rules for targets named gadgetron_grappa

# Build rule for target.
gadgetron_grappa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_grappa
.PHONY : gadgetron_grappa

# fast build rule for target.
gadgetron_grappa/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/grappa/CMakeFiles/gadgetron_grappa.dir/build.make gadgets/grappa/CMakeFiles/gadgetron_grappa.dir/build
.PHONY : gadgetron_grappa/fast

#=============================================================================
# Target rules for targets named gadgetron_dicom

# Build rule for target.
gadgetron_dicom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_dicom
.PHONY : gadgetron_dicom

# fast build rule for target.
gadgetron_dicom/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/dicom/CMakeFiles/gadgetron_dicom.dir/build.make gadgets/dicom/CMakeFiles/gadgetron_dicom.dir/build
.PHONY : gadgetron_dicom/fast

#=============================================================================
# Target rules for targets named gadgetron_cartesian

# Build rule for target.
gadgetron_cartesian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_cartesian
.PHONY : gadgetron_cartesian

# fast build rule for target.
gadgetron_cartesian/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/cartesian/CMakeFiles/gadgetron_cartesian.dir/build.make gadgets/cartesian/CMakeFiles/gadgetron_cartesian.dir/build
.PHONY : gadgetron_cartesian/fast

#=============================================================================
# Target rules for targets named gadgetron_moco

# Build rule for target.
gadgetron_moco: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_moco
.PHONY : gadgetron_moco

# fast build rule for target.
gadgetron_moco/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/moco/CMakeFiles/gadgetron_moco.dir/build.make gadgets/moco/CMakeFiles/gadgetron_moco.dir/build
.PHONY : gadgetron_moco/fast

#=============================================================================
# Target rules for targets named gadgetron_plplot

# Build rule for target.
gadgetron_plplot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_plplot
.PHONY : gadgetron_plplot

# fast build rule for target.
gadgetron_plplot/fast:
	$(MAKE) $(MAKESILENT) -f gadgets/plplot/CMakeFiles/gadgetron_plplot.dir/build.make gadgets/plplot/CMakeFiles/gadgetron_plplot.dir/build
.PHONY : gadgetron_plplot/fast

#=============================================================================
# Target rules for targets named gadgetron

# Build rule for target.
gadgetron: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron
.PHONY : gadgetron

# fast build rule for target.
gadgetron/fast:
	$(MAKE) $(MAKESILENT) -f apps/gadgetron/CMakeFiles/gadgetron.dir/build.make apps/gadgetron/CMakeFiles/gadgetron.dir/build
.PHONY : gadgetron/fast

#=============================================================================
# Target rules for targets named gadgetron_ismrmrd_client

# Build rule for target.
gadgetron_ismrmrd_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gadgetron_ismrmrd_client
.PHONY : gadgetron_ismrmrd_client

# fast build rule for target.
gadgetron_ismrmrd_client/fast:
	$(MAKE) $(MAKESILENT) -f apps/clients/gadgetron_ismrmrd_client/CMakeFiles/gadgetron_ismrmrd_client.dir/build.make apps/clients/gadgetron_ismrmrd_client/CMakeFiles/gadgetron_ismrmrd_client.dir/build
.PHONY : gadgetron_ismrmrd_client/fast

#=============================================================================
# Target rules for targets named cpu_denoise_TV

# Build rule for target.
cpu_denoise_TV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpu_denoise_TV
.PHONY : cpu_denoise_TV

# fast build rule for target.
cpu_denoise_TV/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/cpu/denoising/2d/CMakeFiles/cpu_denoise_TV.dir/build.make apps/standalone/cpu/denoising/2d/CMakeFiles/cpu_denoise_TV.dir/build
.PHONY : cpu_denoise_TV/fast

#=============================================================================
# Target rules for targets named register_HS_2d_cpu

# Build rule for target.
register_HS_2d_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_HS_2d_cpu
.PHONY : register_HS_2d_cpu

# fast build rule for target.
register_HS_2d_cpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/cpu/registration/2d/CMakeFiles/register_HS_2d_cpu.dir/build.make apps/standalone/cpu/registration/2d/CMakeFiles/register_HS_2d_cpu.dir/build
.PHONY : register_HS_2d_cpu/fast

#=============================================================================
# Target rules for targets named register_CK_2d_cpu

# Build rule for target.
register_CK_2d_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_CK_2d_cpu
.PHONY : register_CK_2d_cpu

# fast build rule for target.
register_CK_2d_cpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/cpu/registration/2d/CMakeFiles/register_CK_2d_cpu.dir/build.make apps/standalone/cpu/registration/2d/CMakeFiles/register_CK_2d_cpu.dir/build
.PHONY : register_CK_2d_cpu/fast

#=============================================================================
# Target rules for targets named register_CK_3d_cpu

# Build rule for target.
register_CK_3d_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_CK_3d_cpu
.PHONY : register_CK_3d_cpu

# fast build rule for target.
register_CK_3d_cpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/cpu/registration/3d/CMakeFiles/register_CK_3d_cpu.dir/build.make apps/standalone/cpu/registration/3d/CMakeFiles/register_CK_3d_cpu.dir/build
.PHONY : register_CK_3d_cpu/fast

#=============================================================================
# Target rules for targets named examples_run_cpu

# Build rule for target.
examples_run_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples_run_cpu
.PHONY : examples_run_cpu

# fast build rule for target.
examples_run_cpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/cpu/examples/CMakeFiles/examples_run_cpu.dir/build.make apps/standalone/cpu/examples/CMakeFiles/examples_run_cpu.dir/build
.PHONY : examples_run_cpu/fast

#=============================================================================
# Target rules for targets named nffth_2d_radial

# Build rule for target.
nffth_2d_radial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nffth_2d_radial
.PHONY : nffth_2d_radial

# fast build rule for target.
nffth_2d_radial/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nffth_2d_radial.dir/build.make apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nffth_2d_radial.dir/build
.PHONY : nffth_2d_radial/fast

#=============================================================================
# Target rules for targets named nfft_2d_radial

# Build rule for target.
nfft_2d_radial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nfft_2d_radial
.PHONY : nfft_2d_radial

# fast build rule for target.
nfft_2d_radial/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nfft_2d_radial.dir/build.make apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nfft_2d_radial.dir/build
.PHONY : nfft_2d_radial/fast

#=============================================================================
# Target rules for targets named nffth_cg_2d_radial

# Build rule for target.
nffth_cg_2d_radial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nffth_cg_2d_radial
.PHONY : nffth_cg_2d_radial

# fast build rule for target.
nffth_cg_2d_radial/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nffth_cg_2d_radial.dir/build.make apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nffth_cg_2d_radial.dir/build
.PHONY : nffth_cg_2d_radial/fast

#=============================================================================
# Target rules for targets named nffth_sb_2d_radial

# Build rule for target.
nffth_sb_2d_radial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nffth_sb_2d_radial
.PHONY : nffth_sb_2d_radial

# fast build rule for target.
nffth_sb_2d_radial/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nffth_sb_2d_radial.dir/build.make apps/standalone/gpu/mri/nfft/2d/CMakeFiles/nffth_sb_2d_radial.dir/build
.PHONY : nffth_sb_2d_radial/fast

#=============================================================================
# Target rules for targets named nffth_2d_ms_radial

# Build rule for target.
nffth_2d_ms_radial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nffth_2d_ms_radial
.PHONY : nffth_2d_ms_radial

# fast build rule for target.
nffth_2d_ms_radial/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/ms2d/CMakeFiles/nffth_2d_ms_radial.dir/build.make apps/standalone/gpu/mri/nfft/ms2d/CMakeFiles/nffth_2d_ms_radial.dir/build
.PHONY : nffth_2d_ms_radial/fast

#=============================================================================
# Target rules for targets named nfft_2d_ms_radial

# Build rule for target.
nfft_2d_ms_radial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nfft_2d_ms_radial
.PHONY : nfft_2d_ms_radial

# fast build rule for target.
nfft_2d_ms_radial/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/ms2d/CMakeFiles/nfft_2d_ms_radial.dir/build.make apps/standalone/gpu/mri/nfft/ms2d/CMakeFiles/nfft_2d_ms_radial.dir/build
.PHONY : nfft_2d_ms_radial/fast

#=============================================================================
# Target rules for targets named nffth_2d_ms_generic

# Build rule for target.
nffth_2d_ms_generic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nffth_2d_ms_generic
.PHONY : nffth_2d_ms_generic

# fast build rule for target.
nffth_2d_ms_generic/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/nfft/ms2d/CMakeFiles/nffth_2d_ms_generic.dir/build.make apps/standalone/gpu/mri/nfft/ms2d/CMakeFiles/nffth_2d_ms_generic.dir/build
.PHONY : nffth_2d_ms_generic/fast

#=============================================================================
# Target rules for targets named sense_cg_generic_2d

# Build rule for target.
sense_cg_generic_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sense_cg_generic_2d
.PHONY : sense_cg_generic_2d

# fast build rule for target.
sense_cg_generic_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/sense/noncartesian/CMakeFiles/sense_cg_generic_2d.dir/build.make apps/standalone/gpu/mri/sense/noncartesian/CMakeFiles/sense_cg_generic_2d.dir/build
.PHONY : sense_cg_generic_2d/fast

#=============================================================================
# Target rules for targets named sense_sbc_radial_2d

# Build rule for target.
sense_sbc_radial_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sense_sbc_radial_2d
.PHONY : sense_sbc_radial_2d

# fast build rule for target.
sense_sbc_radial_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_sbc_radial_2d.dir/build.make apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_sbc_radial_2d.dir/build
.PHONY : sense_sbc_radial_2d/fast

#=============================================================================
# Target rules for targets named sense_gpbb_radial_2d

# Build rule for target.
sense_gpbb_radial_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sense_gpbb_radial_2d
.PHONY : sense_gpbb_radial_2d

# fast build rule for target.
sense_gpbb_radial_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_gpbb_radial_2d.dir/build.make apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_gpbb_radial_2d.dir/build
.PHONY : sense_gpbb_radial_2d/fast

#=============================================================================
# Target rules for targets named sense_cg_radial_2d

# Build rule for target.
sense_cg_radial_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sense_cg_radial_2d
.PHONY : sense_cg_radial_2d

# fast build rule for target.
sense_cg_radial_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_cg_radial_2d.dir/build.make apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_cg_radial_2d.dir/build
.PHONY : sense_cg_radial_2d/fast

#=============================================================================
# Target rules for targets named sense_nlcg_radial_2d

# Build rule for target.
sense_nlcg_radial_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sense_nlcg_radial_2d
.PHONY : sense_nlcg_radial_2d

# fast build rule for target.
sense_nlcg_radial_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_nlcg_radial_2d.dir/build.make apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio/CMakeFiles/sense_nlcg_radial_2d.dir/build
.PHONY : sense_nlcg_radial_2d/fast

#=============================================================================
# Target rules for targets named ktsense_radial_2d

# Build rule for target.
ktsense_radial_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktsense_radial_2d
.PHONY : ktsense_radial_2d

# fast build rule for target.
ktsense_radial_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio_kt/CMakeFiles/ktsense_radial_2d.dir/build.make apps/standalone/gpu/mri/sense/noncartesian/radial/2d_golden_ratio_kt/CMakeFiles/ktsense_radial_2d.dir/build
.PHONY : ktsense_radial_2d/fast

#=============================================================================
# Target rules for targets named denoise_TV

# Build rule for target.
denoise_TV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 denoise_TV
.PHONY : denoise_TV

# fast build rule for target.
denoise_TV/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/denoising/2d/CMakeFiles/denoise_TV.dir/build.make apps/standalone/gpu/denoising/2d/CMakeFiles/denoise_TV.dir/build
.PHONY : denoise_TV/fast

#=============================================================================
# Target rules for targets named deblur_2d_cg

# Build rule for target.
deblur_2d_cg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deblur_2d_cg
.PHONY : deblur_2d_cg

# fast build rule for target.
deblur_2d_cg/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/deblurring/2d/CMakeFiles/deblur_2d_cg.dir/build.make apps/standalone/gpu/deblurring/2d/CMakeFiles/deblur_2d_cg.dir/build
.PHONY : deblur_2d_cg/fast

#=============================================================================
# Target rules for targets named blur_2d

# Build rule for target.
blur_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blur_2d
.PHONY : blur_2d

# fast build rule for target.
blur_2d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/deblurring/2d/CMakeFiles/blur_2d.dir/build.make apps/standalone/gpu/deblurring/2d/CMakeFiles/blur_2d.dir/build
.PHONY : blur_2d/fast

#=============================================================================
# Target rules for targets named deblur_2d_sb

# Build rule for target.
deblur_2d_sb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deblur_2d_sb
.PHONY : deblur_2d_sb

# fast build rule for target.
deblur_2d_sb/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/deblurring/2d/CMakeFiles/deblur_2d_sb.dir/build.make apps/standalone/gpu/deblurring/2d/CMakeFiles/deblur_2d_sb.dir/build
.PHONY : deblur_2d_sb/fast

#=============================================================================
# Target rules for targets named deblur_3d_cg

# Build rule for target.
deblur_3d_cg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deblur_3d_cg
.PHONY : deblur_3d_cg

# fast build rule for target.
deblur_3d_cg/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/deblurring/3d/CMakeFiles/deblur_3d_cg.dir/build.make apps/standalone/gpu/deblurring/3d/CMakeFiles/deblur_3d_cg.dir/build
.PHONY : deblur_3d_cg/fast

#=============================================================================
# Target rules for targets named blur_3d

# Build rule for target.
blur_3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blur_3d
.PHONY : blur_3d

# fast build rule for target.
blur_3d/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/deblurring/3d/CMakeFiles/blur_3d.dir/build.make apps/standalone/gpu/deblurring/3d/CMakeFiles/blur_3d.dir/build
.PHONY : blur_3d/fast

#=============================================================================
# Target rules for targets named deblur_3d_sb

# Build rule for target.
deblur_3d_sb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deblur_3d_sb
.PHONY : deblur_3d_sb

# fast build rule for target.
deblur_3d_sb/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/deblurring/3d/CMakeFiles/deblur_3d_sb.dir/build.make apps/standalone/gpu/deblurring/3d/CMakeFiles/deblur_3d_sb.dir/build
.PHONY : deblur_3d_sb/fast

#=============================================================================
# Target rules for targets named register_HS_2d_gpu

# Build rule for target.
register_HS_2d_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_HS_2d_gpu
.PHONY : register_HS_2d_gpu

# fast build rule for target.
register_HS_2d_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/registration/2d/CMakeFiles/register_HS_2d_gpu.dir/build.make apps/standalone/gpu/registration/2d/CMakeFiles/register_HS_2d_gpu.dir/build
.PHONY : register_HS_2d_gpu/fast

#=============================================================================
# Target rules for targets named register_CK_2d_gpu

# Build rule for target.
register_CK_2d_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_CK_2d_gpu
.PHONY : register_CK_2d_gpu

# fast build rule for target.
register_CK_2d_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/registration/2d/CMakeFiles/register_CK_2d_gpu.dir/build.make apps/standalone/gpu/registration/2d/CMakeFiles/register_CK_2d_gpu.dir/build
.PHONY : register_CK_2d_gpu/fast

#=============================================================================
# Target rules for targets named register_CGHS_2d_gpu

# Build rule for target.
register_CGHS_2d_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_CGHS_2d_gpu
.PHONY : register_CGHS_2d_gpu

# fast build rule for target.
register_CGHS_2d_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/registration/2d/CMakeFiles/register_CGHS_2d_gpu.dir/build.make apps/standalone/gpu/registration/2d/CMakeFiles/register_CGHS_2d_gpu.dir/build
.PHONY : register_CGHS_2d_gpu/fast

#=============================================================================
# Target rules for targets named register_CK_3d_gpu

# Build rule for target.
register_CK_3d_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_CK_3d_gpu
.PHONY : register_CK_3d_gpu

# fast build rule for target.
register_CK_3d_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/registration/3d/CMakeFiles/register_CK_3d_gpu.dir/build.make apps/standalone/gpu/registration/3d/CMakeFiles/register_CK_3d_gpu.dir/build
.PHONY : register_CK_3d_gpu/fast

#=============================================================================
# Target rules for targets named examples_run_gpu

# Build rule for target.
examples_run_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples_run_gpu
.PHONY : examples_run_gpu

# fast build rule for target.
examples_run_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/examples/CMakeFiles/examples_run_gpu.dir/build.make apps/standalone/gpu/examples/CMakeFiles/examples_run_gpu.dir/build
.PHONY : examples_run_gpu/fast

#=============================================================================
# Target rules for targets named zerofilling_run_gpu

# Build rule for target.
zerofilling_run_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zerofilling_run_gpu
.PHONY : zerofilling_run_gpu

# fast build rule for target.
zerofilling_run_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/zerofilling/CMakeFiles/zerofilling_run_gpu.dir/build.make apps/standalone/gpu/zerofilling/CMakeFiles/zerofilling_run_gpu.dir/build
.PHONY : zerofilling_run_gpu/fast

#=============================================================================
# Target rules for targets named zerofilling_memcpy_run_gpu

# Build rule for target.
zerofilling_memcpy_run_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zerofilling_memcpy_run_gpu
.PHONY : zerofilling_memcpy_run_gpu

# fast build rule for target.
zerofilling_memcpy_run_gpu/fast:
	$(MAKE) $(MAKESILENT) -f apps/standalone/gpu/zerofilling_memcpy/CMakeFiles/zerofilling_memcpy_run_gpu.dir/build.make apps/standalone/gpu/zerofilling_memcpy/CMakeFiles/zerofilling_memcpy_run_gpu.dir/build
.PHONY : zerofilling_memcpy_run_gpu/fast

#=============================================================================
# Target rules for targets named chroot

# Build rule for target.
chroot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chroot
.PHONY : chroot

# fast build rule for target.
chroot/fast:
	$(MAKE) $(MAKESILENT) -f chroot/CMakeFiles/chroot.dir/build.make chroot/CMakeFiles/chroot.dir/build
.PHONY : chroot/fast

#=============================================================================
# Target rules for targets named chroot_base

# Build rule for target.
chroot_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chroot_base
.PHONY : chroot_base

# fast build rule for target.
chroot_base/fast:
	$(MAKE) $(MAKESILENT) -f chroot/CMakeFiles/chroot_base.dir/build.make chroot/CMakeFiles/chroot_base.dir/build
.PHONY : chroot_base/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... chroot"
	@echo "... chroot_base"
	@echo "... blur_2d"
	@echo "... blur_3d"
	@echo "... cpu_denoise_TV"
	@echo "... deblur_2d_cg"
	@echo "... deblur_2d_sb"
	@echo "... deblur_3d_cg"
	@echo "... deblur_3d_sb"
	@echo "... denoise_TV"
	@echo "... examples_run_cpu"
	@echo "... examples_run_gpu"
	@echo "... gadgetron"
	@echo "... gadgetron_cartesian"
	@echo "... gadgetron_cmr"
	@echo "... gadgetron_core"
	@echo "... gadgetron_core_distributed"
	@echo "... gadgetron_core_parallel"
	@echo "... gadgetron_core_readers"
	@echo "... gadgetron_core_writers"
	@echo "... gadgetron_dicom"
	@echo "... gadgetron_epi"
	@echo "... gadgetron_examples"
	@echo "... gadgetron_fatwater"
	@echo "... gadgetron_gpugadget"
	@echo "... gadgetron_gpuparallelmri"
	@echo "... gadgetron_gpuradial"
	@echo "... gadgetron_grappa"
	@echo "... gadgetron_hyper"
	@echo "... gadgetron_interventional_mri"
	@echo "... gadgetron_ismrmrd_client"
	@echo "... gadgetron_moco"
	@echo "... gadgetron_mri_noncartesian"
	@echo "... gadgetron_mricore"
	@echo "... gadgetron_plplot"
	@echo "... gadgetron_smscore"
	@echo "... gadgetron_spiral"
	@echo "... gadgetron_t1"
	@echo "... gadgetron_test_python"
	@echo "... gadgetron_thermocore"
	@echo "... gadgetron_toolbox_cmr"
	@echo "... gadgetron_toolbox_cpu_image"
	@echo "... gadgetron_toolbox_cpucore"
	@echo "... gadgetron_toolbox_cpucore_math"
	@echo "... gadgetron_toolbox_cpudwt"
	@echo "... gadgetron_toolbox_cpufft"
	@echo "... gadgetron_toolbox_cpuklt"
	@echo "... gadgetron_toolbox_cpunfft"
	@echo "... gadgetron_toolbox_cpuoperator"
	@echo "... gadgetron_toolbox_cpureg"
	@echo "... gadgetron_toolbox_deblur"
	@echo "... gadgetron_toolbox_demons"
	@echo "... gadgetron_toolbox_denoise"
	@echo "... gadgetron_toolbox_fatwater"
	@echo "... gadgetron_toolbox_gpucore"
	@echo "... gadgetron_toolbox_gpudwt"
	@echo "... gadgetron_toolbox_gpufft"
	@echo "... gadgetron_toolbox_gpunfft"
	@echo "... gadgetron_toolbox_gpuoperators"
	@echo "... gadgetron_toolbox_gpuparallelmri"
	@echo "... gadgetron_toolbox_gpureg"
	@echo "... gadgetron_toolbox_gpusolvers"
	@echo "... gadgetron_toolbox_hostutils"
	@echo "... gadgetron_toolbox_hyper"
	@echo "... gadgetron_toolbox_image_analyze_io"
	@echo "... gadgetron_toolbox_log"
	@echo "... gadgetron_toolbox_mri_core"
	@echo "... gadgetron_toolbox_mri_core_python"
	@echo "... gadgetron_toolbox_plplot"
	@echo "... gadgetron_toolbox_pr"
	@echo "... gadgetron_toolbox_python"
	@echo "... gadgetron_toolbox_t1"
	@echo "... ktsense_radial_2d"
	@echo "... nfft_2d_ms_radial"
	@echo "... nfft_2d_radial"
	@echo "... nffth_2d_ms_generic"
	@echo "... nffth_2d_ms_radial"
	@echo "... nffth_2d_radial"
	@echo "... nffth_cg_2d_radial"
	@echo "... nffth_sb_2d_radial"
	@echo "... python_demo"
	@echo "... register_CGHS_2d_gpu"
	@echo "... register_CK_2d_cpu"
	@echo "... register_CK_2d_gpu"
	@echo "... register_CK_3d_cpu"
	@echo "... register_CK_3d_gpu"
	@echo "... register_HS_2d_cpu"
	@echo "... register_HS_2d_gpu"
	@echo "... sense_cg_generic_2d"
	@echo "... sense_cg_radial_2d"
	@echo "... sense_gpbb_radial_2d"
	@echo "... sense_nlcg_radial_2d"
	@echo "... sense_sbc_radial_2d"
	@echo "... zerofilling_memcpy_run_gpu"
	@echo "... zerofilling_run_gpu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

