#ifndef GADGETRON_SMSDEPRECIATED_EXPORT_H_
#define GADGETRON_SMSDEPRECIATED_EXPORT_H_

#if defined (WIN32)
#if defined (__BUILD_GADGETRON_SMSDEPRECIATED__)
#define EXPORTGADGETSSMSDEPRECIATED __declspec(dllexport)
#else
#define EXPORTGADGETSSMSDEPRECIATED __declspec(dllimport)
#endif
#else
#define EXPORTGADGETSSMSDEPRECIATED
#endif

#endif /* GADGETRON_SMSDEPRECIATED_EXPORT_H_ */
